title: CODE CHECK
#email: your-email@example.com
description: >-
  CODE CHECK is a process for independent reproduction of computations and awarding of time-stamped certificates for successful reproductions of scholarly articles.
baseurl: ""
url: "https://codecheck.org.uk/"
author: "Stephen Eglen & Daniel Nüst"

markdown: kramdown
theme: minima-reboot

plugins:
  - jekyll-feed
  - jekyll-seo-tag

license:
  text: CC BY-SA 4.0
  link: https://creativecommons.org/licenses/by-sa/4.0/
  logo: https://mirrors.creativecommons.org/presskit/buttons/88x31/svg/by-sa.svg

# https://github.com/aterenin/minima-reboot/#adding-new-links-to-footer
footer_icons:
  - username: codecheckers
    url: https://github.com/codecheckers/
    icon: icon-github.svg
  #- username: sje30
  #  url: https://github.com/sje30/
  #  icon: icon-github.svg
  #- username: nuest
  #  url: https://github.com/nuest/
  #  icon: icon-github.svg
  - username: StephenEglen
    url: https://twitter.com/StephenEglen
    icon: icon-twitter.svg
  - username: nordholmen
    url: https://twitter.com/nordholmen
    icon: icon-twitter.svg
  - username: S. Eglen
    url: mailto:sje30@cam.ac.uk
    icon: icon-email.svg
  - username: D. Nüst
    url: mailto:daniel.nuest@uni-muenster.de
    icon: icon-email.svg

header_pages:
  - process.md
  - project.md
  - team.md

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - travis.sh
  - .travis.yml
  - Makefile
  - logo
  - badge

error_mode: strict
